before_install:
- openssl aes-256-cbc -K $encrypted_3b9f0b9d36d1_key -iv $encrypted_3b9f0b9d36d1_iv
  -in secrets.tar.enc -out secrets.tar -d
- cd Backend
- npm install
- tar xvf ../secrets.tar
language: node_js
node_js:
- stable
cache:
  directories:
  - "$HOME/.npm"
script:
- npm test
