before_install:
 - cd Backend
 - npm install
 - openssl aes-256-cbc -K $encrypted_3c84dcdc6bbe_key -iv $encrypted_3c84dcdc6bbe_iv -in ../.env.enc -out .env -d
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "$HOME/.npm"
script:
 - npm test
